// Generated by CoffeeScript 1.3.3

$(document).ready(function() {
  var self;
  self = this;
  $('#chocopuyo_planet').click(function() {
    return (function(self) {
      return self.append_minichoco();
    })(self);
  });
  return this.append_minichoco = function() {
    return $('#mini_chocos').append("<img style='width:50px' src='http://chocopuyo.com/images/chocopuyo_planet.png'>");
  };
});
